# automatically generated by the FlatBuffers compiler, do not modify

# namespace: groceryfb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ItemQty(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ItemQty()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsItemQty(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ItemQty
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ItemQty
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ItemQty
    def Qty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ItemQtyStart(builder): builder.StartObject(2)
def Start(builder):
    return ItemQtyStart(builder)
def ItemQtyAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return ItemQtyAddName(builder, name)
def ItemQtyAddQty(builder, qty): builder.PrependInt32Slot(1, qty, 0)
def AddQty(builder, qty):
    return ItemQtyAddQty(builder, qty)
def ItemQtyEnd(builder): return builder.EndObject()
def End(builder):
    return ItemQtyEnd(builder)