# automatically generated by the FlatBuffers compiler, do not modify

# namespace: groceryfb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkOrder(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkOrder()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkOrder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkOrder
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkOrder
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkOrder
    def RequestType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # WorkOrder
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkOrder
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from groceryfb.ItemQty import ItemQty
            obj = ItemQty()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorkOrder
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkOrder
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def WorkOrderStart(builder): builder.StartObject(4)
def Start(builder):
    return WorkOrderStart(builder)
def WorkOrderAddRequestId(builder, requestId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)
def AddRequestId(builder, requestId):
    return WorkOrderAddRequestId(builder, requestId)
def WorkOrderAddRequestType(builder, requestType): builder.PrependInt8Slot(1, requestType, 0)
def AddRequestType(builder, requestType):
    return WorkOrderAddRequestType(builder, requestType)
def WorkOrderAddId(builder, id): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def AddId(builder, id):
    return WorkOrderAddId(builder, id)
def WorkOrderAddItems(builder, items): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)
def AddItems(builder, items):
    return WorkOrderAddItems(builder, items)
def WorkOrderStartItemsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartItemsVector(builder, numElems):
    return WorkOrderStartItemsVector(builder, numElems)
def WorkOrderEnd(builder): return builder.EndObject()
def End(builder):
    return WorkOrderEnd(builder)