# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milestone1/proto/grocery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'milestone1/proto/grocery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emilestone1/proto/grocery.proto\x12\x07grocery\"\xa5\x01\n\x0cOrderRequest\x12*\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x14.grocery.RequestType\x12\n\n\x02id\x18\x02 \x01(\t\x12/\n\x05items\x18\x03 \x03(\x0b\x32 .grocery.OrderRequest.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"?\n\nOrderReply\x12 \n\x04\x63ode\x18\x01 \x01(\x0e\x32\x12.grocery.ReplyCode\x12\x0f\n\x07message\x18\x02 \x01(\t*3\n\x0bRequestType\x12\x11\n\rGROCERY_ORDER\x10\x00\x12\x11\n\rRESTOCK_ORDER\x10\x01*$\n\tReplyCode\x12\x06\n\x02OK\x10\x00\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x01\x32M\n\x10InventoryService\x12\x39\n\x0bSubmitOrder\x12\x15.grocery.OrderRequest\x1a\x13.grocery.OrderReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'milestone1.proto.grocery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST_ITEMSENTRY']._loaded_options = None
  _globals['_ORDERREQUEST_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_REQUESTTYPE']._serialized_start=276
  _globals['_REQUESTTYPE']._serialized_end=327
  _globals['_REPLYCODE']._serialized_start=329
  _globals['_REPLYCODE']._serialized_end=365
  _globals['_ORDERREQUEST']._serialized_start=44
  _globals['_ORDERREQUEST']._serialized_end=209
  _globals['_ORDERREQUEST_ITEMSENTRY']._serialized_start=165
  _globals['_ORDERREQUEST_ITEMSENTRY']._serialized_end=209
  _globals['_ORDERREPLY']._serialized_start=211
  _globals['_ORDERREPLY']._serialized_end=274
  _globals['_INVENTORYSERVICE']._serialized_start=367
  _globals['_INVENTORYSERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
